### ISSUE TITLE
Accuracy is low using open-room mic

### ISSUE THREAD

**Issue by DDews** [miguelmota/pocketsphinxjs-multiple-keywords#2]
We're getting good results using a headset or desk mic, but when we try using this with our open-room mic, we're getting very low accuracy.

I'd say we get 1 out of 10 tries resulting in a successful hotword detection on an open-room mic, when it's more like 1:1 or 1:2 for headset.

I've looked into increasing the noise energy threshold in vad.js from the example, but it doesn't seem to do anything. I put console.logs for function entrance in vad.js and none of them ever seem to be called.

I am guessing vad.js is used with regular keyword detection like in pocketsphinx js's example, but not in multiple keyword detection when we compile our own pocketsphinx.js like we do following this example.

We've made the sensitivity for keyword phrases to 1e-100 for all keyword phrases. We still have a low accuracy issue.

Do you have any knowledge in how to increase our accuracy further?

**Comment by miguelmota** [comment]
@DDews you might have to re-train the acoustic models. You can try using pocketsphinx from the command line using multiple keywords to see if the issue is reproducible. I suggest asking on the pocketsphinx forums and see if they'll provide some guidance
