### ISSUE TITLE
How to call function when word is detected?

### ISSUE THREAD

**Issue by AlecHaring** [miguelmota/pocketsphinxjs-multiple-keywords#3]
Where would I call a function when a word is detected with keyword spotting? Like if I wanted to make a sound every time the user says the keyword

**Comment by miguelmota** [comment]
@Siralland01 probably after you get a new hypothesis like here https://github.com/miguelmota/pocketsphinxjs-multiple-keywords/blob/master/example/scripts/main.js#L174 if you're following the example in repo

**Comment by AlecHaring** [comment]
Thanks for the suggestion. I figured it out yesterday, but that is how I did it
