### ISSUE TITLE
New Keyword List and Dict Files 

### ISSUE THREAD

**Issue by Archetype90** [miguelmota/pocketsphinxjs-multiple-keywords#4]
First of all, thank you so much for the great repository explaining how to use multiple keywords. It was a great explanation and guide. But, I do not understand something. Let me try to describe what I have done.

1. Cloned your repository
2. Creating kws.dict and kws.list with different words (forward, previous, open) 
3. Compiled Pocketsphinx.js with my kws.dict
4. Compiled kws-list.js using my kws.list file 
5. Replace keyphrase-list.js with kws-list.js in the repository 
6. Replace references to keyphrase-list.js with kws-list.js and /keyphrase.list to /kws.list

At this point when I run the code I get an error that it cannot find forward, previous, and open in the dictionary. This makes sense - it is opening the list and comparing it to your old keyphrase.dict, which does not contain those words. 

So, I replace the pocketsphinx.js that is located in the repository with my new pocketsphinx.js that contains my kws.dict file. This new pocketsphinx.js file has a reference to "createDataFile" similar to what is seen in the kws-list.js. This new pocketsphinx.js references the kws.dict. After replacing the file I change the --dict parameter to /kws.dict.

After running I get an error that "no file named kws.dict" could be found. When I change the --dict parameter back to keyphrases.dict the error goes back to "could not find forward, previous, and open in the dictionary". 

So - my question - where is the keyphrases.dict file coming from? My original thought was that the pocketsphinx.js was creating it, similar to how the kws-list.js is creating the kws.list. But that does not seem to be right. When I search the repository I find references to that file in three places - 

1. The README
2. The Pocketsphinx.js file
3. The main.js --dict parameter

But I have removed the pocketsphinx.js file and replaced it with mine (that tries to create kws.dict) and replaced the --dict parameter with kws.dict. 

After posting this I am going to attempt compiling PS without a dictionary, having a file called kws.dict, and passing that in as a parameter, but I would love to understand this problem still. Thanks for any help you can provide!

**Comment by Archetype90** [comment]
Well, I have solved this problem, but I am leaving the issue open since I still not do fully understand how your source code is working.

My solution was to generate the dict as a JS file, in the same manner that the list file was generated. I then load that in as another data script, which generates the dict, and the code has no problem reading it. I still really do not understand where your dict object is located.

**Comment by miguelmota** [comment]
> So - my question - where is the keyphrases.dict file coming from? 

@Archetype90 you specify the dict file when running `cmake`: `-DDICT_FILES= keyphrases.dict`. After compilation and running `make`, the generated `pocketsphinx.js` will contain the dictionary *embedded*. Therefore `keyphrases.dict` in the JavaScript is just a key name and doesn't reference the actual file, it references the embedded dictionary.

This screenshot shows `keyphrases.dict` is the name to references the embedded library, so in theory it can be called whatever you'd like. The `.dict` is what's confusing making it seem like it's references an actual file.

<img width="976" alt="screen shot 2018-06-20 at 11 41 31 am" src="https://user-images.githubusercontent.com/168240/41678084-ed6b0164-747e-11e8-8c72-a04413fa5c9b.png">

**Comment by Archetype90** [comment]
@miguelmota Thank you for the response. In my original question I mentioned that I had done the steps that you suggest in your response (compiling PS.js with a new .dict file), but I am clearly missing something. Let me walk you through what I am doing and hopefully you can identify where I am making my mistake.

1. Clone your repository
2. Serve the files (python3 -m http.server)
3. Navigate to the website and everything works great. Cat, dog, fish can be identified. 
4. Build Pocketsphinx.js with my new keyphrase.dict that includes three different words 
        - Using the instructions from your ReadMe
5. Create a new keyphrase-list.js with my own keyphrases 
        - Using the instructions from your ReadMe
6. Copy new pocketsphinx.js file that was built into the /scripts/ directory
7. Copy the new keyphrase-list.js into the /scripts/ directory 
7. Serve and navigate to the website

Here is where things break apart, after replacing only the pocketsphinx.js file I start to receive the following errors:

![image](https://user-images.githubusercontent.com/14015661/41783390-9709ac0c-75f1-11e8-8aff-60863da37e03.png)

Now, the .wasm one is very explicit, but still confusing. I did not build it as a web assembly (according to their docs, we did not use the -DWASM=ON flag. But even if I add that file, I still see the following errors:

![image](https://user-images.githubusercontent.com/14015661/41783503-d6bf082e-75f1-11e8-8943-32c8fff61c7f.png)

Have I missed a step? Done one of the steps wrong? I am really at a loss as to what is causing these issues and how to update PS to use a different dictionary.

**Comment by Archetype90** [comment]
Another small update. If I do the following, I can get everything working with my own custom dictionary and list files:

1. Clone your repository
2. Generate a kws-dict.js and kws-list.js file using the method in your ReadMe
3. Copy the kws-dict and kws-list files to the /scripts/ folder
4. Change file references to /kws.list and /kws.dict
5. Add /scripts/kws-dict.js to the data section after line 140

I then server the website and it no longer recognizes your words and does recognize my words. This did not involve rebuilding PS.. but I have never seen this method done anywhere else, either in your repository or the official repository, so I do not believe this is the correct way to do this. Plus, I would like to understand what I am doing wrong with the building process.

I then rebuilt PS.js with no dictionary, copied it over, and saw the same errors as the above post. Copied the PS.js that you complied back and everything works fine again. Something is wrong with whatever I am doing to compile PS.js. 

Thanks again for any insight you can provide.
